services:
  accounts:
    image: "praveen36999/accounts:s2"
    container_name: "accounts_microservice"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 600m
    networks:
      - bank-network
  loans:
    image: "praveen36999/loans:s2"
    container_name: "loans_microservice"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - bank-network
  cards:
    image: "praveen36999/cards:s2"
    container_name: "cards_microservice"
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - bank-network
networks:
  bank-network:
    driver: bridge