build:
  version: "2.0"
accounts:
  message: "Welcome to Eazybank accounts related qa APIs"
  contactDetails:
      name: "nitherson-qa"
      email: "nitherson@eazybank.com"
  onCallSupport:
      -(555)555-1234
      -(555)523-1345


