build:
  version: "1.0"
accounts:
  message: "Welcome to Eazybank accounts related prod APIs"
  contactDetails:
      name: "akash-prod"
      email: "akash@eazybank.com"
  onCallSupport:
      -(555)555-1234
      -(555)523-1345


