build:
  version: "2.0"
loans:
  message: "Welcome to Eazybank loans related qa APIs"
  contactDetails:
      name: "nitherson-qa"
      email: "nitherson@eazybank.com"
  onCallSupport:
      -(555)555-1234
      -(555)523-1345


